create table MIGRATION_LOG
(
    MIGRATION_DATE DATE   default SYSDATE not null,
    ID             NUMBER default "CHERNY"."ISEQ$$_79933".nextval generated as identity
)
/

INSERT INTO CHERNY.MIGRATION_LOG (MIGRATION_DATE, ID) VALUES (TO_DATE('2021-08-09 11:32:42', 'YYYY-MM-DD HH24:MI:SS'), 90);
INSERT INTO CHERNY.MIGRATION_LOG (MIGRATION_DATE, ID) VALUES (TO_DATE('2021-08-09 11:36:13', 'YYYY-MM-DD HH24:MI:SS'), 91);